
INSERT INTO public.publisher (publisher_name) VALUES ('Rockstar Games');
INSERT INTO public.publisher (publisher_name) VALUES ('CD PROJEKT RED');
INSERT INTO public.publisher (publisher_name) VALUES ('Electronic Arts');
INSERT INTO public.publisher (publisher_name) VALUES ('Valve');
INSERT INTO public.publisher (publisher_name) VALUES ('Square Enix');
INSERT INTO public.publisher (publisher_name) VALUES ('Bethesda Softworks');
INSERT INTO public.publisher (publisher_name) VALUES ('2K Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Activision Blizzard');
INSERT INTO public.publisher (publisher_name) VALUES ('Sony Interactive Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Microsoft Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('505 Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Sony Computer Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Capcom');
INSERT INTO public.publisher (publisher_name) VALUES ('Psyonix');
INSERT INTO public.publisher (publisher_name) VALUES ('Digital Extremes');
INSERT INTO public.publisher (publisher_name) VALUES ('Deep Silver');
INSERT INTO public.publisher (publisher_name) VALUES ('Konami');
INSERT INTO public.publisher (publisher_name) VALUES ('Warner Bros. Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('1C-SoftClub');
INSERT INTO public.publisher (publisher_name) VALUES ('Telltale Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Feral Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Team Cherry');
INSERT INTO public.publisher (publisher_name) VALUES ('Bandai Namco Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Devolver Digital');
INSERT INTO public.publisher (publisher_name) VALUES ('Red Barrels');
INSERT INTO public.publisher (publisher_name) VALUES ('Ubisoft Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Chucklefish');
INSERT INTO public.publisher (publisher_name) VALUES ('Frictional Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Grinding Gear Games');
INSERT INTO public.publisher (publisher_name) VALUES ('THQ');
INSERT INTO public.publisher (publisher_name) VALUES ('KRAFTON');
INSERT INTO public.publisher (publisher_name) VALUES ('SEGA');
INSERT INTO public.publisher (publisher_name) VALUES ('Ninja Theory');
INSERT INTO public.publisher (publisher_name) VALUES ('Klei Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Studio Wildcard');
INSERT INTO public.publisher (publisher_name) VALUES ('Supergiant Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Hi-Rez Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Paradox Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Campo Santo');
INSERT INTO public.publisher (publisher_name) VALUES ('Activison');
INSERT INTO public.publisher (publisher_name) VALUES ('THQ Nordic');
INSERT INTO public.publisher (publisher_name) VALUES ('Hello Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Innersloth');
INSERT INTO public.publisher (publisher_name) VALUES ('New World Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Frozenbyte');
INSERT INTO public.publisher (publisher_name) VALUES ('GameOn');
INSERT INTO public.publisher (publisher_name) VALUES ('3909');
INSERT INTO public.publisher (publisher_name) VALUES ('Warhorse Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Plug In Digital');
INSERT INTO public.publisher (publisher_name) VALUES ('Unknown Worlds Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Buka Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Techland Publishing');
INSERT INTO public.publisher (publisher_name) VALUES ('DrinkBox Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Annapurna Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Perfect World Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Raw Fury');
INSERT INTO public.publisher (publisher_name) VALUES ('Running With Scissors');
INSERT INTO public.publisher (publisher_name) VALUES ('Private Division');
INSERT INTO public.publisher (publisher_name) VALUES ('Team17 Digital');
INSERT INTO public.publisher (publisher_name) VALUES ('Endnight Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Crowbar Collective');
INSERT INTO public.publisher (publisher_name) VALUES ('Matt Makes Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Team Salvato');
INSERT INTO public.publisher (publisher_name) VALUES ('Nicalis');
INSERT INTO public.publisher (publisher_name) VALUES ('Muse Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Kalypso Media');
INSERT INTO public.publisher (publisher_name) VALUES ('The Chinese Room');
INSERT INTO public.publisher (publisher_name) VALUES ('Focus Home Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Fellow Traveller');
INSERT INTO public.publisher (publisher_name) VALUES ('Aspyr');
INSERT INTO public.publisher (publisher_name) VALUES ('Night School Studio');
INSERT INTO public.publisher (publisher_name) VALUES ('Majesco Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Daybreak Game Company');
INSERT INTO public.publisher (publisher_name) VALUES ('Daedalic Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Reto-Moto');
INSERT INTO public.publisher (publisher_name) VALUES ('VRChat');
INSERT INTO public.publisher (publisher_name) VALUES ('Codemasters');
INSERT INTO public.publisher (publisher_name) VALUES ('Larian Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Disney Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Berserk Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Amanita Design');
INSERT INTO public.publisher (publisher_name) VALUES ('Stardock Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Coffee Stain');
INSERT INTO public.publisher (publisher_name) VALUES ('Xbox Game Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Freejam');
INSERT INTO public.publisher (publisher_name) VALUES ('Koch Media');
INSERT INTO public.publisher (publisher_name) VALUES ('11 bit studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Facepunch Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('GT Interactive Software');
INSERT INTO public.publisher (publisher_name) VALUES ('Hinterland Studio');
INSERT INTO public.publisher (publisher_name) VALUES ('GSC Game World');
INSERT INTO public.publisher (publisher_name) VALUES ('Introversion Software');
INSERT INTO public.publisher (publisher_name) VALUES ('Thunder Lotus Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Tripwire Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('BetaDwarf');
INSERT INTO public.publisher (publisher_name) VALUES ('Coffee Stain Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Alawar Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Humble Bundle');
INSERT INTO public.publisher (publisher_name) VALUES ('Curve Digital');
INSERT INTO public.publisher (publisher_name) VALUES ('Jackbox Games');
INSERT INTO public.publisher (publisher_name) VALUES ('8-4');
INSERT INTO public.publisher (publisher_name) VALUES ('Stunlock Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('All in! Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Playsaurus');
INSERT INTO public.publisher (publisher_name) VALUES ('Soviet Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Bossa Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('TaleWorlds Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Fatshark');
INSERT INTO public.publisher (publisher_name) VALUES ('TopWare Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('miHoYo');
INSERT INTO public.publisher (publisher_name) VALUES ('Versus Evil');
INSERT INTO public.publisher (publisher_name) VALUES ('Wargaming');
INSERT INTO public.publisher (publisher_name) VALUES ('Crate Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('tinyBuild');
INSERT INTO public.publisher (publisher_name) VALUES ('Brilliant Game Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Bohemia Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('WarChest');
INSERT INTO public.publisher (publisher_name) VALUES ('Lever Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Gameforge 4D');
INSERT INTO public.publisher (publisher_name) VALUES ('Abylight');
INSERT INTO public.publisher (publisher_name) VALUES ('The Indie Stone');
INSERT INTO public.publisher (publisher_name) VALUES ('Flippfly');
INSERT INTO public.publisher (publisher_name) VALUES ('Greenheart Games');
INSERT INTO public.publisher (publisher_name) VALUES ('PlayStation Mobile');
INSERT INTO public.publisher (publisher_name) VALUES ('Automaton');
INSERT INTO public.publisher (publisher_name) VALUES ('Wube Software');
INSERT INTO public.publisher (publisher_name) VALUES ('NeocoreGames');
INSERT INTO public.publisher (publisher_name) VALUES ('Data Realms');
INSERT INTO public.publisher (publisher_name) VALUES ('Total Mayhem Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Statespace');
INSERT INTO public.publisher (publisher_name) VALUES ('Reverb Communications');
INSERT INTO public.publisher (publisher_name) VALUES ('Amazon Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Chibig');
INSERT INTO public.publisher (publisher_name) VALUES ('Funcom');
INSERT INTO public.publisher (publisher_name) VALUES ('Terry Cavanagh');
INSERT INTO public.publisher (publisher_name) VALUES ('Poysky Productions');
INSERT INTO public.publisher (publisher_name) VALUES ('Gearbox Publishing');
INSERT INTO public.publisher (publisher_name) VALUES ('Blizzard Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Trendy Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Tencent Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Edge Case Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Almost Human Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Beamdog');
INSERT INTO public.publisher (publisher_name) VALUES ('Keen Software House');
INSERT INTO public.publisher (publisher_name) VALUES ('Tomorrow');
INSERT INTO public.publisher (publisher_name) VALUES ('Landfall');
INSERT INTO public.publisher (publisher_name) VALUES ('Ludeon Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('AQUIRIS');
INSERT INTO public.publisher (publisher_name) VALUES ('Suspicious Developments');
INSERT INTO public.publisher (publisher_name) VALUES ('Double Fine Productions');
INSERT INTO public.publisher (publisher_name) VALUES ('Sumo Digital');
INSERT INTO public.publisher (publisher_name) VALUES ('Frontier Developments');
INSERT INTO public.publisher (publisher_name) VALUES ('SNK');
INSERT INTO public.publisher (publisher_name) VALUES ('Axolot Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Pillow Castle Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Tate Multimedia');
INSERT INTO public.publisher (publisher_name) VALUES ('Trek Industries');
INSERT INTO public.publisher (publisher_name) VALUES ('Prism Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('The Game Creators');
INSERT INTO public.publisher (publisher_name) VALUES ('Defiant Development');
INSERT INTO public.publisher (publisher_name) VALUES ('HandyGames');
INSERT INTO public.publisher (publisher_name) VALUES ('DotEmu');
INSERT INTO public.publisher (publisher_name) VALUES ('Shiver Games');
INSERT INTO public.publisher (publisher_name) VALUES ('The Fullbright Company');
INSERT INTO public.publisher (publisher_name) VALUES ('Crunching Koalas');
INSERT INTO public.publisher (publisher_name) VALUES ('Failbetter Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Deca Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Double Damage Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Colibri Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Nightdive Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Asteroid Base');
INSERT INTO public.publisher (publisher_name) VALUES ('PlayWay');
INSERT INTO public.publisher (publisher_name) VALUES ('Midway Home Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('NEOWIZ');
INSERT INTO public.publisher (publisher_name) VALUES ('Atari');
INSERT INTO public.publisher (publisher_name) VALUES ('Kyle Seeley');
INSERT INTO public.publisher (publisher_name) VALUES ('Soedesco');
INSERT INTO public.publisher (publisher_name) VALUES ('Kiss');
INSERT INTO public.publisher (publisher_name) VALUES ('Young Horses');
INSERT INTO public.publisher (publisher_name) VALUES ('Oculus Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Fruitbat Factory');
INSERT INTO public.publisher (publisher_name) VALUES ('GRASSHOPPER MANUFACTURE');
INSERT INTO public.publisher (publisher_name) VALUES ('Crytek');
INSERT INTO public.publisher (publisher_name) VALUES ('Mode 7');
INSERT INTO public.publisher (publisher_name) VALUES ('Ember Lab');
INSERT INTO public.publisher (publisher_name) VALUES ('Ska Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Reactive Drop Team');
INSERT INTO public.publisher (publisher_name) VALUES ('Standing Stone Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Image & Form');
INSERT INTO public.publisher (publisher_name) VALUES ('Sven Co-op Team');
INSERT INTO public.publisher (publisher_name) VALUES ('CI Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Gun Media');
INSERT INTO public.publisher (publisher_name) VALUES ('Everything Unlimited');
INSERT INTO public.publisher (publisher_name) VALUES ('Kloonigames');
INSERT INTO public.publisher (publisher_name) VALUES ('Vlambeer');
INSERT INTO public.publisher (publisher_name) VALUES ('EA Originals');
INSERT INTO public.publisher (publisher_name) VALUES ('Team Reptile');
INSERT INTO public.publisher (publisher_name) VALUES ('Monolith Productions');
INSERT INTO public.publisher (publisher_name) VALUES ('WayForward');
INSERT INTO public.publisher (publisher_name) VALUES ('Merge Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Rusty Lake');
INSERT INTO public.publisher (publisher_name) VALUES ('Supra Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Aksys Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Size Five Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Atlus');
INSERT INTO public.publisher (publisher_name) VALUES ('Games Operators');
INSERT INTO public.publisher (publisher_name) VALUES ('Sierra Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Konfa Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Alawar Premium');
INSERT INTO public.publisher (publisher_name) VALUES ('Triternion');
INSERT INTO public.publisher (publisher_name) VALUES ('Sekai Project');
INSERT INTO public.publisher (publisher_name) VALUES ('Capybara Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Astragon Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('EnjoyUp Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Bloober Team');
INSERT INTO public.publisher (publisher_name) VALUES ('THE BROTHERHOOD');
INSERT INTO public.publisher (publisher_name) VALUES ('Tortuga Team');
INSERT INTO public.publisher (publisher_name) VALUES ('Grip Digital sro');
INSERT INTO public.publisher (publisher_name) VALUES ('FireFly Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Big Fat Alien');
INSERT INTO public.publisher (publisher_name) VALUES ('Streum On Studio');
INSERT INTO public.publisher (publisher_name) VALUES ('Hemisphere Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Adult Swim Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Red 5 Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Rebellion');
INSERT INTO public.publisher (publisher_name) VALUES ('Broken Rules');
INSERT INTO public.publisher (publisher_name) VALUES ('Gaslamp Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Senscape');
INSERT INTO public.publisher (publisher_name) VALUES ('Bennett Foddy');
INSERT INTO public.publisher (publisher_name) VALUES ('Codename Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Lazy 8 Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Robot Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Sharkmob');
INSERT INTO public.publisher (publisher_name) VALUES ('Bifrost Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Wolfire');
INSERT INTO public.publisher (publisher_name) VALUES ('Focus Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Meridian4');
INSERT INTO public.publisher (publisher_name) VALUES ('Nintendo');
INSERT INTO public.publisher (publisher_name) VALUES ('Wales Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Vivendi Universal Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Atlus USA');
INSERT INTO public.publisher (publisher_name) VALUES ('Koei Tecmo Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Noodlecake Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('Virgin Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Playrise Digital');
INSERT INTO public.publisher (publisher_name) VALUES ('Good Shepherd Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('PlayStack');
INSERT INTO public.publisher (publisher_name) VALUES ('Tonguç Bodur');
INSERT INTO public.publisher (publisher_name) VALUES ('Microids');
INSERT INTO public.publisher (publisher_name) VALUES ('AGM PLAYISM');
INSERT INTO public.publisher (publisher_name) VALUES ('NVIDIA');
INSERT INTO public.publisher (publisher_name) VALUES ('Arkane Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('RuneStorm');
INSERT INTO public.publisher (publisher_name) VALUES ('Misfits Attic');
INSERT INTO public.publisher (publisher_name) VALUES ('Mastfire Studios');
INSERT INTO public.publisher (publisher_name) VALUES ('DL Softworks');
INSERT INTO public.publisher (publisher_name) VALUES ('Zeboyd Games');
INSERT INTO public.publisher (publisher_name) VALUES ('Stitch Heads Entertainment');
INSERT INTO public.publisher (publisher_name) VALUES ('Sunken Treasure Games');
INSERT INTO public.publisher (publisher_name) VALUES ('MercurySteam');
INSERT INTO public.publisher (publisher_name) VALUES ('Oddworld Inhabitants');
INSERT INTO public.publisher (publisher_name) VALUES ('Vertigo Gaming');
INSERT INTO public.publisher (publisher_name) VALUES ('Degica');
INSERT INTO public.publisher (publisher_name) VALUES ('Strategy First');
INSERT INTO public.publisher (publisher_name) VALUES ('Yukitama Creative Industries');
INSERT INTO public.publisher (publisher_name) VALUES ('INFORMATION SOLUTIONS GROUP');
INSERT INTO public.publisher (publisher_name) VALUES ('Eyebrow Interactive');
INSERT INTO public.publisher (publisher_name) VALUES ('Wired Productions');
INSERT INTO public.publisher (publisher_name) VALUES ('Chasing Carrots');
INSERT INTO public.publisher (publisher_name) VALUES ('Tequila Works');
INSERT INTO public.publisher (publisher_name) VALUES ('Edmund McMillen');
INSERT INTO public.publisher (publisher_name) VALUES ('Funbox Media');
INSERT INTO public.publisher (publisher_name) VALUES ('Forever Entertainment');


--
-- TOC entry 5010 (class 0 OID 49773)
-- Dependencies: 241
-- Data for Name: publisher_game; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 1);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (2, 2);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 3);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 4);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 5);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 6);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 7);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 8);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 9);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 10);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 11);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 12);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 13);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 14);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 15);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 16);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 17);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 18);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 19);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 20);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 21);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (2, 22);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 23);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 24);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 25);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 26);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (14, 27);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (15, 28);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 29);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 30);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (17, 31);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 32);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 33);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (19, 34);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 35);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (19, 36);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 37);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 38);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 39);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 40);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 41);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (22, 42);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 43);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 44);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 45);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 49);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 50);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 51);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 52);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (25, 53);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 54);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 55);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 56);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 57);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 58);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 59);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (27, 60);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (28, 61);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 62);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (29, 63);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 64);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (30, 65);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (31, 66);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 67);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 68);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 69);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 70);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 71);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 72);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 73);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 74);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 75);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 76);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 77);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 78);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 79);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 80);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (33, 81);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 82);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 83);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (34, 84);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 85);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 86);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 87);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 88);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 89);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 90);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 91);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 92);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 93);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 96);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 97);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 98);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 99);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 100);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 101);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (35, 102);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (36, 103);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (37, 104);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 105);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 106);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 107);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 108);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 109);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 110);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 111);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 112);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 113);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 114);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 115);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (39, 116);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (40, 117);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 118);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 119);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 120);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 121);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 122);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (36, 123);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (42, 124);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 125);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 126);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 127);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (43, 128);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (44, 130);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (40, 131);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 132);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 133);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 134);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (45, 135);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 136);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 137);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (28, 138);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 139);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (28, 140);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 141);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 142);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 143);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (46, 144);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (47, 145);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (48, 146);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 147);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 148);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (49, 149);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 150);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 151);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 152);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 153);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 154);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (50, 155);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 156);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 157);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 158);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (51, 159);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 160);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 161);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (52, 162);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 163);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 164);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (53, 165);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 166);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 167);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 168);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (54, 169);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (55, 170);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 171);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 172);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 173);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (56, 174);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 175);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 176);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 177);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 178);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 179);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 180);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 181);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (57, 182);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 183);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 184);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (58, 185);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 186);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 187);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 188);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 189);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 190);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 192);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 193);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (60, 194);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 195);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (17, 196);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 197);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (61, 198);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (62, 199);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 200);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (63, 201);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (64, 202);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 203);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (65, 204);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 205);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (66, 206);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 207);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 208);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (67, 209);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 210);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 211);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (69, 212);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 213);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (70, 214);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 215);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 216);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (30, 217);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (27, 218);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (45, 219);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 220);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (55, 221);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 222);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 224);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 226);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 227);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 228);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 229);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 230);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 231);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 232);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (71, 233);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 234);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 235);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 236);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 237);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (72, 238);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 239);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 240);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (73, 241);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 242);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 243);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 244);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 245);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (74, 246);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 247);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (75, 248);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 249);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 250);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 251);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 252);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (76, 253);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 254);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (77, 255);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (78, 256);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 257);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (40, 258);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 259);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (79, 260);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (80, 261);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 262);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 263);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (81, 264);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 265);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 266);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 267);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 268);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 269);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (54, 270);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (82, 271);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (83, 272);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 273);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (84, 274);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 275);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 276);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 277);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 278);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 279);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 280);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 281);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (54, 282);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 283);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 284);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 285);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 286);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (25, 287);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 288);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 289);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (85, 290);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 291);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 292);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (86, 293);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 294);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (87, 295);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 296);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 297);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 298);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 299);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (88, 300);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (89, 301);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (90, 302);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (91, 303);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 304);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 305);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (77, 306);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 307);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (92, 308);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (93, 309);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (84, 310);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 311);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 312);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (94, 313);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 314);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (95, 315);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (96, 316);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (97, 317);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 318);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 319);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 320);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (98, 321);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 322);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 323);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 324);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (100, 325);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (101, 326);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 327);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (2, 328);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 329);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 330);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 331);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 332);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (77, 333);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (96, 334);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 335);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 341);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 342);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (102, 343);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 344);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (49, 345);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 346);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 347);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 348);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 349);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (103, 350);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (104, 351);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 352);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (105, 353);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 354);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 355);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 356);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (106, 357);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 358);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (107, 359);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 360);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 361);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (108, 362);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 363);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 364);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 365);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (58, 366);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 367);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (109, 368);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (49, 369);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (110, 370);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (1, 371);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 372);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (111, 373);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 374);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 375);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 376);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 377);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 378);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 379);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (112, 380);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 381);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (34, 382);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (113, 383);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 384);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 385);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (114, 386);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 387);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 388);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 389);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (115, 390);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 391);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 392);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 393);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (116, 394);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 395);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 396);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (117, 397);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (118, 398);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (119, 399);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 400);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 401);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 402);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (55, 403);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 404);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 405);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 406);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (66, 407);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 408);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 409);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (120, 410);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (121, 411);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 412);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 413);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (122, 414);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 415);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 416);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 417);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (123, 418);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 419);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 420);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (77, 421);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (124, 422);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 423);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (125, 424);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 425);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 426);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 427);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 428);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (87, 429);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (126, 430);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 431);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 432);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (127, 433);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 434);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 436);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (128, 437);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 438);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 439);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (37, 440);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 441);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (40, 442);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (129, 443);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 444);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (40, 445);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 446);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 447);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 448);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (130, 449);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 450);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (131, 451);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (132, 452);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (133, 453);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (70, 454);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 455);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 456);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (87, 457);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (134, 458);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 459);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 460);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (135, 461);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 462);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 463);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 464);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 465);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 466);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 467);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 468);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (136, 469);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (137, 470);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 471);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 472);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (138, 473);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 474);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 475);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (53, 476);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 477);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 478);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (56, 479);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (139, 480);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (70, 481);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (52, 482);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (70, 483);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (78, 484);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 486);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (140, 487);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 488);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 490);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 491);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 492);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 493);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (141, 494);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (142, 495);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 496);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 497);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 498);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 499);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (36, 500);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (82, 501);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (137, 502);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 503);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 504);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 505);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 506);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (143, 507);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (144, 508);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (145, 509);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 510);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (146, 511);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (147, 512);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 513);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 514);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (18, 515);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (109, 516);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 517);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 518);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (148, 519);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (84, 520);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (149, 521);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (19, 522);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 523);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 524);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (114, 525);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (150, 526);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 527);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 528);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (151, 529);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (70, 530);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 531);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 532);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 533);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (50, 534);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 535);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 536);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 537);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (152, 538);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (109, 539);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 540);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (152, 541);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 542);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 543);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (153, 544);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 545);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 546);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (134, 547);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (154, 548);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (155, 549);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 550);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (156, 551);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (157, 552);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (114, 553);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (158, 554);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 555);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (159, 556);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 557);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 558);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (160, 559);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (161, 560);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (79, 561);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 562);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 563);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (162, 564);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (163, 565);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (164, 566);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 567);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (49, 568);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (165, 569);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 570);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (166, 571);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 572);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (45, 573);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (167, 574);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 575);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 576);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (168, 577);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (4, 578);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 579);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 580);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (169, 581);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (170, 582);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (96, 583);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (171, 584);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 585);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 586);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (172, 587);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (94, 588);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (173, 589);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 590);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (174, 591);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (175, 592);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 593);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 594);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 595);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 596);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (176, 597);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (78, 598);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (177, 599);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 600);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 601);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 602);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 603);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (55, 604);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (178, 605);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (179, 606);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 607);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (180, 608);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 609);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 610);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 611);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 612);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 613);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 614);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 615);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 616);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 617);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (181, 618);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 619);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 620);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (56, 621);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (28, 622);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 623);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (182, 624);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 625);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (138, 626);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (183, 627);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 628);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (184, 629);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (185, 630);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 631);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (27, 632);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (186, 633);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 634);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 635);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (187, 636);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (188, 637);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 638);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (189, 639);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 640);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (190, 641);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 642);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (191, 643);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (192, 644);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (193, 645);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (194, 646);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 647);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (195, 648);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 649);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (196, 650);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 651);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 652);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 653);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 654);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 655);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 656);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 657);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (38, 658);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 659);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (197, 660);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 661);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 662);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (198, 663);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (62, 664);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (199, 665);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (200, 666);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (201, 667);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (202, 668);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 669);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (170, 670);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 671);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (114, 672);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (203, 673);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (204, 674);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (205, 675);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (74, 676);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (45, 677);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 678);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 679);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (112, 680);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 681);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (200, 682);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 683);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 684);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (206, 685);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (207, 686);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 687);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (208, 688);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (209, 689);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (92, 690);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (210, 691);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (211, 692);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (212, 693);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 694);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 695);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 696);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 697);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 698);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 699);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 700);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (213, 701);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 702);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (159, 703);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (87, 705);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (200, 706);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (56, 707);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (11, 708);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (214, 709);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (215, 710);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (216, 711);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (217, 712);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 713);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (218, 714);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (54, 716);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 718);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (219, 719);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (99, 720);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (32, 721);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 723);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 724);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 725);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (220, 726);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (221, 727);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (16, 728);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (222, 729);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (9, 730);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (79, 731);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (74, 732);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (64, 733);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 734);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (223, 735);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (92, 736);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 737);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (224, 738);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (114, 739);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 740);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 741);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 742);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (77, 743);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (205, 744);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (74, 745);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (225, 746);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (226, 747);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (227, 748);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (228, 749);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (229, 750);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (230, 751);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (231, 752);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (232, 753);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (233, 754);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 755);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 756);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (13, 757);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 758);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (68, 759);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (74, 760);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (234, 761);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (235, 762);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (236, 763);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (20, 764);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (237, 765);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (238, 766);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (239, 767);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (64, 768);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (240, 769);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (19, 770);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (241, 771);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (242, 772);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (243, 773);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (8, 774);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (244, 775);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 776);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (238, 777);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (245, 778);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (55, 779);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (7, 781);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 782);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (246, 783);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (247, 784);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (248, 785);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (249, 786);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (108, 787);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (127, 788);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (24, 789);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (23, 790);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (40, 791);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (250, 792);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (129, 793);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (251, 794);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (252, 795);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (26, 796);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 797);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (91, 798);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (238, 799);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (41, 800);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (253, 801);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (66, 802);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (254, 803);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (114, 804);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (73, 805);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 806);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 807);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (6, 808);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (255, 809);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (102, 810);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (256, 811);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (257, 812);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (17, 814);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (258, 815);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (178, 816);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (259, 817);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (12, 818);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (260, 819);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (81, 820);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (261, 821);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (59, 822);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (262, 823);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (263, 824);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (3, 825);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (142, 826);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (28, 827);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (21, 828);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (264, 829);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (93, 830);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (265, 831);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (100, 832);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (266, 833);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (85, 834);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (267, 835);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (268, 836);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (5, 837);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (74, 838);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (10, 839);
INSERT INTO public.publisher_game (publisher_id,game_id) VALUES (269, 840);
