INSERT INTO public.address (postal_code,city,address) VALUES ('85498', 'McCulloughborough', '52382 Barton Lock');
INSERT INTO public.address (postal_code,city,address) VALUES ('55629', 'North Brunotown', '46834 Kiehn Drive');
INSERT INTO public.address (postal_code,city,address) VALUES ('29385-3805', 'New Margorie', '81829 Goldner Cliff');
INSERT INTO public.address (postal_code,city,address) VALUES ('55629', 'North Brunotown', '399 Deangelo Meadows');
INSERT INTO public.address (postal_code,city,address) VALUES ('00996', 'East Blytheborough', '35200 Blair Trace');
INSERT INTO public.address (postal_code,city,address) VALUES ('26595', 'Leeburgh', '81829 Goldner Cliff');
INSERT INTO public.address (postal_code,city,address) VALUES ('55629', 'North Brunotown', '35200 Blair Trace');
INSERT INTO public.address (postal_code,city,address) VALUES ('26595', 'Leeburgh', '05222 Earle Junction');
INSERT INTO public.address (postal_code,city,address) VALUES ('01244-7167', 'East Farahport', '4482 Dede Ville');
INSERT INTO public.address (postal_code,city,address) VALUES ('65386-7067', 'Gibsonfurt', '05727 Rory Roads');
INSERT INTO public.address (postal_code,city,address) VALUES ('01244-7167', 'East Farahport', '459 Kimi Forges');
INSERT INTO public.address (postal_code,city,address) VALUES ('05970-2716', 'North Tammiechester', '08235 Lucy Walks');
INSERT INTO public.address (postal_code,city,address) VALUES ('62444', 'West Silas', '93259 Tayna Glen');
INSERT INTO public.address (postal_code,city,address) VALUES ('65386-7067', 'Gibsonfurt', '459 Kimi Forges');
INSERT INTO public.address (postal_code,city,address) VALUES ('62444', 'West Silas', '40556 Trinidad Expressway');
INSERT INTO public.address (postal_code,city,address) VALUES ('05970-2716', 'North Tammiechester', '459 Kimi Forges');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '294 Kelley Mountains');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '6375 O''Connell Row');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '556 Charlena Rest');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '30725 Kertzmann Inlet');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '96149 Kautzer Rapid');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '6028 Roman Square');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '96149 Kautzer Rapid');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '6375 O''Connell Row');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '052 Jame Creek');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '30725 Kertzmann Inlet');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '08278 Lemke Mall');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '294 Kelley Mountains');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '9183 Graham Flat');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '556 Charlena Rest');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '556 Charlena Rest');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '039 Olson Club');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '9183 Graham Flat');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '26737 Mueller Path');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '98307 Funk Vista');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '556 Charlena Rest');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '76624 Stanford Lake');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '96149 Kautzer Rapid');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '294 Kelley Mountains');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '9183 Graham Flat');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '9782 Upton Extension');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '052 Jame Creek');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '9782 Upton Extension');
INSERT INTO public.address (postal_code,city,address) VALUES ('30033-6149', 'East Latanyafort', '755 Robbi Walk');
INSERT INTO public.address (postal_code,city,address) VALUES ('65055-0792', 'Franeckichester', '470 Caren Valley');
INSERT INTO public.address (postal_code,city,address) VALUES ('80498-9323', 'North Percy', '6375 O''Connell Row');
INSERT INTO public.address (postal_code,city,address) VALUES ('39265-3307', 'West Frankie', '30725 Kertzmann Inlet');
INSERT INTO public.address (postal_code,city,address) VALUES ('70363', 'West Edmond', '6370 Sari Road');
INSERT INTO public.address (postal_code,city,address) VALUES ('19319', 'East Sydney', '7442 Treutel Plain');
INSERT INTO public.address (postal_code,city,address) VALUES ('68953', 'Aldostad', '586 Emmerich Track');
INSERT INTO public.address (postal_code,city,address) VALUES ('68953', 'Aldostad', '792 Beahan Square');
INSERT INTO public.address (postal_code,city,address) VALUES ('67124', 'Klingchester', '43386 Conn Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('78539-7545', 'Rempelview', '245 Claud Ports');
INSERT INTO public.address (postal_code,city,address) VALUES ('78539-7545', 'Rempelview', '350 Kieth Summit');
INSERT INTO public.address (postal_code,city,address) VALUES ('59279', 'Greenfelderstad', '350 Kieth Summit');
INSERT INTO public.address (postal_code,city,address) VALUES ('78539-7545', 'Rempelview', '020 Hermiston Village');
INSERT INTO public.address (postal_code,city,address) VALUES ('78539-7545', 'Rempelview', '627 Amanda Green');
INSERT INTO public.address (postal_code,city,address) VALUES ('59279', 'Greenfelderstad', '557 Del Island');
INSERT INTO public.address (postal_code,city,address) VALUES ('05031', 'Johnsburgh', '557 Del Island');
INSERT INTO public.address (postal_code,city,address) VALUES ('05031', 'Johnsburgh', '3162 Venetta Dale');
INSERT INTO public.address (postal_code,city,address) VALUES ('67943-4270', 'Dinorahmouth', '557 Del Island');
INSERT INTO public.address (postal_code,city,address) VALUES ('05031', 'Johnsburgh', '9309 Kozey Ridges');
INSERT INTO public.address (postal_code,city,address) VALUES ('78539-7545', 'Rempelview', '020 Hermiston Village');
INSERT INTO public.address (postal_code,city,address) VALUES ('59279', 'Greenfelderstad', '0724 Jefferey Valleys');
INSERT INTO public.address (postal_code,city,address) VALUES ('78539-7545', 'Rempelview', '627 Amanda Green');
INSERT INTO public.address (postal_code,city,address) VALUES ('67913-4628', 'North Claudine', '4824 Morgan Trace');
INSERT INTO public.address (postal_code,city,address) VALUES ('12508-9737', 'Joeybury', '41479 Stanley Gateway');
INSERT INTO public.address (postal_code,city,address) VALUES ('17603-5632', 'Leviview', '427 Willms Field');
INSERT INTO public.address (postal_code,city,address) VALUES ('17603-5632', 'Leviview', '4824 Morgan Trace');
INSERT INTO public.address (postal_code,city,address) VALUES ('07495-6159', 'Samualburgh', '1077 Block Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('55780', 'Wisozkmouth', '39546 Windler Oval');
INSERT INTO public.address (postal_code,city,address) VALUES ('07495-6159', 'Samualburgh', '801 Wilburn Light');
INSERT INTO public.address (postal_code,city,address) VALUES ('07495-6159', 'Samualburgh', '5954 Aleen Mews');
INSERT INTO public.address (postal_code,city,address) VALUES ('07495-6159', 'Samualburgh', '5954 Aleen Mews');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '720 Ronald Ferry');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '1192 Corwin Green');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '164 Bauch Stravenue');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '78029 Ledner Island');
INSERT INTO public.address (postal_code,city,address) VALUES ('07495-6159', 'Samualburgh', '556 Schaden Row');
INSERT INTO public.address (postal_code,city,address) VALUES ('55780', 'Wisozkmouth', '96708 Patty Ville');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '760 Bradtke Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '78029 Ledner Island');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '760 Bradtke Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '583 O''Connell Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('07495-6159', 'Samualburgh', '1077 Block Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('45512-4419', 'South Arlethaside', '1504 Blanda Road');
INSERT INTO public.address (postal_code,city,address) VALUES ('09037-9189', 'Sporerside', '8604 Ja Meadows');
INSERT INTO public.address (postal_code,city,address) VALUES ('44556', 'Port Emile', '6202 Judson Garden');
INSERT INTO public.address (postal_code,city,address) VALUES ('09037-9189', 'Sporerside', '779 Hintz Mountains');
INSERT INTO public.address (postal_code,city,address) VALUES ('20737', 'South Faustino', '07331 Hermann Mews');
INSERT INTO public.address (postal_code,city,address) VALUES ('44556', 'Port Emile', '426 Streich Parkway');
INSERT INTO public.address (postal_code,city,address) VALUES ('59091', 'Heathcotefurt', '18816 Mana Summit');
INSERT INTO public.address (postal_code,city,address) VALUES ('44556', 'Port Emile', '07331 Hermann Mews');
INSERT INTO public.address (postal_code,city,address) VALUES ('09037-9189', 'Sporerside', '26449 Merrill Plain');
INSERT INTO public.address (postal_code,city,address) VALUES ('44556', 'Port Emile', '5998 Wunsch Valley');
INSERT INTO public.address (postal_code,city,address) VALUES ('20737', 'South Faustino', '932 Marci Tunnel');
INSERT INTO public.address (postal_code,city,address) VALUES ('93475', 'North Scarlettton', '592 Enid Walks');
INSERT INTO public.address (postal_code,city,address) VALUES ('93475', 'North Scarlettton', '991 Lissa Pike');
INSERT INTO public.address (postal_code,city,address) VALUES ('79876', 'Sharrichester', '087 Sallie Walk');
INSERT INTO public.address (postal_code,city,address) VALUES ('79876', 'Sharrichester', '90741 Bradtke Hollow');
INSERT INTO public.address (postal_code,city,address) VALUES ('93475', 'North Scarlettton', '2721 Green Prairie');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '82894 Leo Trafficway');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '95305 Nikolaus Crossing');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '82894 Leo Trafficway');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '02644 Emelda Dale');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '996 Fritsch Harbor');
INSERT INTO public.address (postal_code,city,address) VALUES ('49244-8152', 'South Raleighchester', '6558 Rempel Hollow');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '07750 Calandra Route');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '76716 Dietrich Highway');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '116 Elmo Corners');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '864 Freeda Mill');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '76716 Dietrich Highway');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '7372 Easter Vista');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '996 Fritsch Harbor');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '864 Freeda Mill');
INSERT INTO public.address (postal_code,city,address) VALUES ('49244-8152', 'South Raleighchester', '116 Elmo Corners');
INSERT INTO public.address (postal_code,city,address) VALUES ('28482', 'North Clinton', '572 Adams Meadows');
INSERT INTO public.address (postal_code,city,address) VALUES ('48376-6952', 'East Agnes', '037 Toy Stream');
INSERT INTO public.address (postal_code,city,address) VALUES ('48376-6952', 'East Agnes', '6558 Rempel Hollow');
INSERT INTO public.address (postal_code,city,address) VALUES ('49244-8152', 'South Raleighchester', '900 Bauch Island');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '572 Adams Meadows');
INSERT INTO public.address (postal_code,city,address) VALUES ('32395', 'Rodneymouth', '38198 Long Gateway');

